

GET http://localhost:8080/todos
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5kb2VAZ21haWwuY29tIiwidXNlcm5hbWUiOiJqb2huIGRvZSIsImlhdCI6MTY2OTY0MzUyMSwiZXhwIjoxNjY5NjQzNjQxfQ.bmCh-qqrYAA5Gsv-fhnya1rYqqXAH6hOq8K4YeNI6KI

###
GET http://localhost:4000/todos
###
POST http://localhost:8080/todos
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5kb2VAZ21haWwuY29tIiwidXNlcm5hbWUiOiJqb2huIGRvZSIsImlhdCI6MTY2OTY0MzUyMSwiZXhwIjoxNjY5NjQzNjQxfQ.bmCh-qqrYAA5Gsv-fhnya1rYqqXAH6hOq8K4YeNI6KI
Content-Type: application/json

{
    "title":"Code",
    "description":"intergrate frontend to backend",
    "date":"2022-11-28"
}


###
PUT http://localhost:4000/todos/sdfhdhdhvjfdhn
Content-Type: application/json

{
    "title":"Updated Code",
    "description":"Updated solve a bug",
    "date":"2022-11-25"
}

###

DELETE http://localhost:4000/todos/c566beff-0eee-4350-b9d9-037c9b1f762b


###
POST http://localhost:8080/user/signup
Content-Type: application/json

{
    "username":"john doe",
    "email":"johndoe@gmail.com",
    "password":"12345678"
}


###
POST http://localhost:8080/user/login
Content-Type: application/json

{
    "email":"johndoe@gmail.com",
    "password":"12345678"
}


###

GET http://localhost:8080/user/home
token: